### ISSUE TITLE
Encountered fatal error while building

### ISSUE THREAD

**Issue by VVSRwastaken** [ZantetsukenGT/AttDef#1]
PS C:\Users\Admin\Desktop\AttDef-1.37.11> sampctl build
C:\Users\Admin\Desktop\AttDef-1.37.11\dependencies\gBugFix\gBugFix.inc:78 (warning) tag mismatch: expected tag none ("_"), but found "PLAYER_STATE"
C:\Users\Admin\Desktop\AttDef-1.37.11\legacy\modules\impl\common.inc:183 (warning) tag mismatch: expected tag "bool", but found none ("_")
C:\Users\Admin\Desktop\AttDef-1.37.11\legacy\modules\impl\common.inc:189 (warning) tag mismatch: expected tag "bool", but found none ("_")
C:\Users\Admin\Desktop\AttDef-1.37.11\legacy\modules\impl\common.inc:1165 (error) undefined symbol "iterstart@VehicleOccupant"
C:\Users\Admin\Desktop\AttDef-1.37.11\legacy\modules\impl\common.inc:1165 (error) undefined symbol "Iter_Func@VehicleOccupant"
C:\Users\Admin\Desktop\AttDef-1.37.11\legacy\modules\impl\common.inc:1165 (error) array must be indexed (variable "Iterator@VehicleOccupant")
C:\Users\Admin\Desktop\AttDef-1.37.11\legacy\modules\impl\common.inc:1165 (fatal) too many error messages on one line
Build encountered fatal error

Verbose output does not add anything more about these specific errors

**Comment by ZantetsukenGT** [comment]
Y-Less updated YSI a few days ago and changed the iterator's name, take a look https://github.com/pawn-lang/YSI-Includes/commit/190df6ad3bab99d72a9fec62b5c34181422b6e3b

I'll update this dw

**Comment by ZantetsukenGT** [comment]
fixed
