### ISSUE TITLE
Prefire algorithm idea

### ISSUE THREAD

**Issue by fedfomin** [ZantetsukenGT/AttDef#4]
This script is pretty easy and defines a threshold of 20.0 degrees, which would be the maximum allowed difference between the players view angle and crosshair angle, when a players view angle and crosshair angle differ more than this threshold, the player is flagged for prefiring and an admin would need to review the case or ask the player to save his point of view.

```
#define PREFIRE_THRESHOLD 20.0

public OnPlayerUpdate(playerid)
{
    new Float:viewAngle, Float:crosshairAngle;
    GetPlayerAim(playerid, viewAngle); // to return the angle at which a player is facing
    GetPlayerFacingAngle(playerid, crosshairAngle); //  to capture the players view angle, also known as the view angles

    if (abs(viewAngle - crosshairAngle) > PREFIRE_THRESHOLD)
    {
        "You have been flagged for prefiring. Admins will review the case." // send message
    }
    return 1;
}
```

Obviously you should need to define functions like GetPlayerAim and GetPlayerFacingAngle (posted an idea of how it can be done), this is a simple example cause you may want to improve this by adding also more advanced checks and logging, such as recording the players position and velocity at the time of the violation etc..

For the function GetPlayerAim i believe something like this could be done

```
forward GetPlayerAim(playerid, Float:&viewAngle);

public GetPlayerAim(playerid, Float:&viewAngle)
{
    viewAngle = GetPlayerCameraFrontVector(playerid); // to get the front vector of the camera (if it does exist in samp)
}
```

GetAimFunction

```
forward GetPlayerAim(playerid, Float:&viewAngle);

public GetPlayerAim(playerid, Float:&viewAngle)
{
    new Float:x, Float:y, Float:z;
    GetPlayerPos(playerid, x, y, z);
    GetPlayerFacingAngle(playerid, viewAngle); // returns the angle at which a player is facing
}
```
These are simple examples but i believe it can be done right ? , tell me what do you think

**Comment by ZantetsukenGT** [comment]
Closing since its a long forgotten, incomplete and now irrelevant idea and the user retired from the AAD scene.
